package cuserr

import "errors"

var (
	// ErrNotFound ...
	ErrNotFound = errors.New("no such record")
	// ErrServiceNotFound ...
	ErrServiceNotFound = errors.New("service not found")
	// ErrServiceNotAvailable ...
	ErrServiceNotAvailable = errors.New("service not available")
	// ErrBadAddress ...
	ErrBadAddress = errors.New("bad address")
	// ErrBadParams ...
	ErrBadParams = errors.New("bad params")
)
